### ISSUE TITLE
Strange naming convention for nBins > 1 datacards + crashes due to the "observed" parameter

### ISSUE THREAD

**Issue by vukasinmilosevic** [vukasinmilosevic/Fiducial_XS#7]
@ram1123 reported an issue that the last step crashes. 

This is due to the mismatch in the datacard folder names for nBins > 1. The hardcoded templates use English grammar and switch to *bins folders for nBins > 1. This will be fixed in the datacard maker in a bit.

After the fix, a new issue arrises as the code complains regarding the "observed" parameter in the datacard:
```
[INFO]: runHZZFiducialXS.py#275 command:
	combineCards.py hzz4l_2e2muS_13TeV_xs_pT4l_bin0_v2.txt hzz4l_2e2muS_13TeV_xs_pT4l_bin1_v2.txt hzz4l_2e2muS_13TeV_xs_pT4l_bin2_v2.txt hzz4l_2e2muS_13TeV_xs_pT4l_bin3_v2.txt hzz4l_2e2muS_13TeV_xs_pT4l_bin4_v2.txt hzz4l_2e2muS_13TeV_xs_pT4l_bin5_v2.txt hzz4l_2e2muS_13TeV_xs_pT4l_bin6_v2.txt hzz4l_2e2muS_13TeV_xs_pT4l_bin7_v2.txt hzz4l_2e2muS_13TeV_xs_pT4l_bin8_v2.txt > hzz4l_2e2muS_13TeV_xs_pT4l_bin_v2.txt
Traceback (most recent call last):
  File "CMSSW_10_2_13/bin/slc7_amd64_gcc700/combineCards.py", line 69, in <module>
    DC = parseCard(file, options)
  File "CMSSW_10_2_13/python/HiggsAnalysis/CombinedLimit/DatacardParser.py", line 119, in parseCard
    if len(ret.obs) != nbins: raise RuntimeError, "Found %d observations but %d bins have been declared" % (len(ret.obs), nbins)
RuntimeError: Error reading line 8 of file hzz4l_2e2muS_13TeV_xs_pT4l_bin0_v2.txt: Found 1 observations but 9 bins have been declared
``` 

Investigation is ongoing and this issue will be dealt with in a follow up PR

**Comment by vukasinmilosevic** [comment]
Fixed with #8
